default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  # password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  # host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %> # `db` is the service name in Docker Compose

development:
  <<: *default
  database: colterlevi_development

test:
  <<: *default
  database: colterlevi_test

production:
  primary:
    <<: *default
    database: colterlevi_production
  cache:
    <<: *default
    database: colterlevi_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: colterlevi_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: colterlevi_production_cable
    migrations_paths: db/cable_migrate
